/*
 * Licensed to the Apache Software Foundation (ASF) under one 
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY 
 * KIND, either express or implied.  See the License for the 
 * specific language governing permissions and limitations
 * under the License.
 */
package org.opencloudengine.garuda.cloud.controller.domain;

import java.io.Serializable;
import java.util.Arrays;
import java.util.Properties;

/**
 * Holds information about a Member.
 */
public class MemberContext implements Serializable {

    private static final long serialVersionUID = -388327475844701869L;

    // Cluster id of this member
    private final String clusterId;
    // Instance id generated by the IaaS
    private String instanceId;

    // Default private ip address
    private String defaultPrivateIP;
    // Private ips
    private String[] privateIPs;
    // Default public ip address
    private String defaultPublicIP;
    // Public ips
    private String[] publicIPs;
    // Manually allocated ips
    private String[] allocatedIPs;

    // Member initiated time
    private long initTime;
    // LB cluster id of this member
    private String lbClusterId;
    // Network partition id
    private String networkPartitionId;
    // Member expiry period on the topology
    private long obsoleteExpiryTime;
    // Member obsolete init time
    private long obsoleteInitTime;
    // Instance metadata generated by the IaaS
    private InstanceMetadata instanceMetadata;
    // Properties
    private Properties properties;

    public MemberContext(String clusterId) {
        this.clusterId = clusterId;
        this.properties = new Properties();
    }

    public String getClusterId() {
        return clusterId;
    }

    public String getDefaultPublicIP() {
        return defaultPublicIP;
    }

    public void setDefaultPublicIP(String defaultPublicIP) {
        this.defaultPublicIP = defaultPublicIP;
    }

    public String[] getPublicIPs() {
        return publicIPs;
    }

    public void setPublicIPs(String[] publicIPs) {
        this.publicIPs = publicIPs;
    }

    public String getDefaultPrivateIP() {
        return defaultPrivateIP;
    }

    public void setDefaultPrivateIP(String defaultPrivateIP) {
        this.defaultPrivateIP = defaultPrivateIP;
    }

    public String[] getPrivateIPs() {
        return privateIPs;
    }

    public void setPrivateIPs(String[] privateIPs) {
        this.privateIPs = privateIPs;
    }

    public String[] getAllocatedIPs() {
        return allocatedIPs;
    }

    public void setAllocatedIPs(String[] allocatedIPs) {
        this.allocatedIPs = allocatedIPs;
    }

    public long getInitTime() {
        return initTime;
    }

    public void setInitTime(long initTime) {
        this.initTime = initTime;
    }

    public String getLbClusterId() {
        return lbClusterId;
    }

    public void setLbClusterId(String lbClusterId) {
        this.lbClusterId = lbClusterId;
    }

    public String getNetworkPartitionId() {
        return networkPartitionId;
    }

    public void setNetworkPartitionId(String networkPartitionId) {
        this.networkPartitionId = networkPartitionId;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result
                + ((clusterId == null) ? 0 : clusterId.hashCode());
        result = prime * result + ((instanceId == null) ? 0 : instanceId.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        MemberContext other = (MemberContext) obj;
        if (getClusterId().equals(other.getClusterId()) &&
                getInstanceId().equals(other.getInstanceId())) {
            return true;
        }
        return false;
    }

    public String getInstanceId() {
        return instanceId;
    }

    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId;
    }

    public long getObsoleteExpiryTime() {
        return obsoleteExpiryTime;
    }

    public void setObsoleteExpiryTime(long obsoleteExpiryTime) {
        this.obsoleteExpiryTime = obsoleteExpiryTime;
    }

    public long getObsoleteInitTime() {
        return obsoleteInitTime;
    }

    public void setObsoleteInitTime(long obsoleteInitTime) {
        this.obsoleteInitTime = obsoleteInitTime;
    }

    public Properties getProperties() {
        return properties;
    }

    public void setProperties(Properties properties) {
        this.properties = properties;
    }

    public InstanceMetadata getInstanceMetadata() {
        return instanceMetadata;
    }

    public void setInstanceMetadata(InstanceMetadata instanceMetadata) {
        this.instanceMetadata = instanceMetadata;
    }

    @Override
    public String toString() {
        return "MemberContext ["
                + ", clusterId=" + clusterId
                + ", instanceId=" + instanceId
                + ", defaultPrivateIP=" + defaultPrivateIP
                + ", defaultPublicIP=" + defaultPublicIP
                + ", allocatedIPs=" + Arrays.toString(allocatedIPs)
                + ", publicIPs=" + Arrays.toString(publicIPs)
                + ", privateIPs=" + Arrays.toString(privateIPs)
                + ", initTime=" + initTime
                + ", lbClusterId=" + lbClusterId
                + ", networkPartitionId=" + networkPartitionId
                + ", instanceMetadata=" + instanceMetadata
                + ", properties=" + properties + "]";
    }
}
